[package]
name = "dna"
version = "0.7.0-alpha.0"
edition = "2021"
rust-version = "1.69"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
depthai-viewer.workspace = true

itertools = "0.10"
rand = "0.8"
