[package]
name = "dna"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
depthai-viewer.workspace = true

itertools = { workspace = true }
rand = "0.8"
