[package]
name = "raw_mesh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
depthai-viewer = { workspace = true, features = ["web_viewer"] }

anyhow.workspace = true
bytes = "1.3"
clap = { workspace = true, features = ["derive"] }
gltf.workspace = true
mimalloc.workspace = true
