[package]
name = "minimal_options"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
depthai-viewer = { workspace = true, features = ["web_viewer"] }

anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
glam.workspace = true
